linters-settings:
  typecheck:
    exclude:
      - "config/config.go" # configのgo embedをスキップするため

issues:
  exclude-files:
    - config/config.go # configのgo embedをスキップするため
run:
  timeout: 5m # デフォルトで1分程度でタイムアウトしてしまうため
